# configs/default.yaml
dataset: cifar10
data_dir: data
model: resnet18
epochs: 2
batch: 1024
workers: 16
seed: 42
warmup: 60
repeat: 600
outbase: baseline_40e
pruned_name: resnet18_struct30
prune_ratio: 0.3
prune_epochs: 10
bundle_zip: showcase_bundle.zip
# set true if you want to run streamlit demo at the end (requires demo_app.py)
open_streamlit: false
