dataset: cifar10
data_dir: data

# Baseline/training knobs (kept here for completeness)
model: resnet18
epochs: 5
batch: 1024
workers: 8
seed: 42

# Bench settings
warmup: 60
repeat: 600

# Pruning metadata (already produced)
pruned_name: resnet18_struct30

# Phase-3 toggles
enable_kd: true
enable_quant_ptq: true
enable_quant_qat: false  # flip to true when ready

kd:
  teacher_ckpt: runs/baseline/best.pt
  teacher: resnet18
  student: mobilenet_v2
  epochs: 2         # smoke
  batch: 512
  workers: 8
  lr: 0.2
  alpha: 0.5
  temperature: 4.0
  outdir: runs/kd_mobilenetv2

quant:
  ptq:
    calib_batches: 8  # smoke
  qat:
    epochs: 1         # smoke
  outdir: runs/quantized

