dataset: cifar10
data_dir: data
model: resnet18
epochs: 2
batch: 1024
workers: 8
seed: 42
warmup: 60
repeat: 600
outbase: baseline_40e
pruned_name: resnet18_struct30
prune_ratio: 0.3
prune_epochs: 10
bundle_zip: showcase_bundle.zip
open_streamlit: false

# Phase-3+ toggles (won't be executed unless your run.py uses them)
enable_kd: false
enable_quant_ptq: false
enable_quant_qat: false

kd:
  teacher: resnet34
  student: mobilenet_v2
  epochs: 10
  batch: 512
  workers: 8
  lr: 0.2
  alpha: 0.5
  temperature: 4.0
  outdir: runs/kd_mobilenetv2

quant:
  ptq:
    calib_batches: 64
  qat:
    epochs: 5
  outdir: runs/quantized
